#!/bin/bash
#PBS -N build.pbs
#PBS -q paidq
#PBS -P 95b3beda-8f4a-41a6-ac94-0aaad86bfd9d
#PBS -M RSCCoreApp@seattlechildrens.org
#PBS -l select=1:mem=16gb:ncpus=1
#PBS -j oe
#PBS -m a
#PBS -o /active/taylor_s/build/RP/bamboo_template/logs/

set -eou pipefail

# bamboo automation assumes workingdir is environment variable TEMP_DIR passed in from qsub -v
if [[ -d $TEMP_DIR ]]; then { echo "SUCCESS: found TEMP_DIR=$TEMP_DIR"; } else { echo "ERROR: couldn't find TEMP_DIR=$TEMP_DIR"; exit 1; } fi
cd $TEMP_DIR

echo "Do build stuff"

echo "create artifact dir"
mkdir -p artifacts

echo "place build artifacts into artifacts dir"
echo "bar" > artifacts/foo.txt

exit